-- SQL REPETITION

-- TASK1
SELECT LOC, MIN(HIREDATE) AS "MIN" FROM EMP INNER JOIN DEPT ON DEPT.DEPTNO=EMP.DEPTNO
  GROUP BY LOC;

-- TASK2
SELECT * FROM EMP
  WHERE SAL>(SELECT MAX(SAL) FROM EMP INNER JOIN DEPT ON DEPT.DEPTNO=EMP.DEPTNO WHERE LOC='DALLAS');

-- TASK3
SELECT COUNT(EMPNO), DEPTNO FROM EMP
  WHERE LENGTH(ENAME)=4
  GROUP BY DEPTNO;

-- TASK4
SELECT DNAME FROM EMP INNER JOIN DEPT ON DEPT.DEPTNO=EMP.DEPTNO
  WHERE SAL = (SELECT AVG(SAL) FROM EMP, SALGRADE WHERE SAL BETWEEN LOSAL AND HISAL AND GRADE=1);

-- TASK5
SELECT E.ENAME, COUNT(E.EMPNO) FROM EMP E, EMP M
  WHERE M.MGR=E.EMPNO
  GROUP BY E.ENAME
  ORDER BY COUNT(E.EMPNO);

-- TASK6
SELECT LOC FROM DEPT
  UNION
SELECT DNAME FROM DEPT;

-- TASK7
SELECT DEPTNO, AVG(SAL), AVG(NVL(COMM, 0)) FROM EMP
  GROUP BY DEPTNO
  HAVING AVG(SAL)<AVG(NVL(COMM, 0));

-- TASK8
SELECT GRADE, COUNT(*) AS ILE FROM EMP, SALGRADE
  WHERE SAL BETWEEN LOSAL AND HISAL
  HAVING COUNT(*) < 1
  GROUP BY GRADE;

-- TASK9
SELECT ENAME, SAL, LOC FROM EMP E INNER JOIN DEPT ON E.DEPTNO=DEPT.DEPTNO
  WHERE SAL=(SELECT MAX(SAL) FROM EMP, DEPT WHERE E.DEPTNO=DEPT.DEPTNO);

-- TASK10
SELECT LOC, GRADE, COUNT(EMPNO) FROM EMP, DEPT, SALGRADE
  WHERE SAL BETWEEN LOSAL AND HISAL AND EMP.DEPTNO=DEPT.DEPTNO
  GROUP BY GRADE, LOC;