-- SQL4

-- TASK1
SELECT ENAME, SAL FROM EMP
  WHERE SAL=(SELECT MIN(SAL) FROM EMP);

-- TASK2
SELECT * FROM EMP
  WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='BLAKE');

-- TASK3
SELECT * FROM EMP
  WHERE SAL IN(SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO);

-- TASK4
SELECT * FROM EMP E
  WHERE E.SAL=(SELECT MIN(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);

-- TASK5
SELECT * FROM EMP
  WHERE SAL>ANY(SELECT MIN(SAL) FROM EMP WHERE DEPTNO=20);

-- TASK6
SELECT * FROM EMP
  WHERE SAL>ALL(SELECT MAX(SAL) FROM EMP WHERE DEPTNO=30);

-- TASK7
SELECT DEPTNO, AVG(SAL) FROM EMP
  GROUP BY DEPTNO
  HAVING AVG(SAL)>(SELECT AVG(SAL) FROM EMP WHERE DEPTNO=30);

-- TASK8
SELECT JOB, AVG(SAL) FROM EMP
  GROUP BY JOB
  HAVING AVG(SAL)=(SELECT MAX(AVG(SAL)) FROM EMP GROUP BY JOB);

-- TASK9
SELECT ENAME, SAL FROM EMP
  WHERE SAL>(SELECT MAX(SAL) FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
  WHERE DEPT.DNAME = 'SALES'
  GROUP BY EMP.DEPTNO);

-- TASK10
SELECT ENAME, SAL FROM EMP E
  WHERE SAL>(SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO GROUP BY DEPTNO);

-- TASK11
SELECT ENAME FROM EMP E
  WHERE EXISTS(SELECT MGR FROM EMP WHERE MGR=E.EMPNO);

-- TASK12
SELECT DISTINCT DEPTNO FROM EMP
  WHERE DEPTNO NOT IN (SELECT DEPTNO FROM DEPT);

-- TASK13
SELECT ENAME, SAL FROM EMP
  WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY JOB)
  ORDER BY SAL DESC;

-- TASK14
SELECT ENAME, SAL FROM EMP
  WHERE SAL IN (SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO)
  ORDER BY ENAME ASC;

-- TASK15
SELECT DEPTNO, ENAME, HIREDATE FROM EMP
  WHERE HIREDATE IN (SELECT MIN(HIREDATE) FROM EMP GROUP BY DEPTNO)
  ORDER BY HIREDATE DESC;

-- TASK16
SELECT ENAME, SAL, DEPTNO FROM EMP E
  WHERE SAL>(SELECT AVG(SAL) FROM EMP WHERE E.DEPTNO = DEPTNO)
  ORDER BY DEPTNO;

-- TASK17
SELECT DEPTNO FROM DEPT
MINUS
SELECT DISTINCT DEPTNO FROM EMP;

-- TASK18
SELECT * FROM (SELECT * FROM EMP ORDER BY SAL DESC)
  WHERE ROWNUM<=3;

-- TASK19
SELECT * FROM (SELECT DEPTNO, COUNT(EMPNO) FROM EMP GROUP BY DEPTNO ORDER BY COUNT(EMPNO) DESC)
  WHERE ROWNUM=1;

-- TASK20
SELECT ENAME, SAL, DEPTNO FROM EMP E
  WHERE SAL>(SELECT AVG(SAL) FROM EMP WHERE E.DEPTNO=DEPTNO GROUP BY DEPTNO);