-- SQL2

-- TASK1
SELECT * FROM EMP
  INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

-- TASK2
SELECT ENAME, DNAME FROM EMP
  INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
  ORDER BY ENAME ASC;

-- TASK3
SELECT ENAME, DNAME, EMP.DEPTNO FROM EMP
  INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

-- TASK4
SELECT ENAME, LOC, DNAME FROM EMP
  INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
  WHERE SAL>1500;

SELECT ENAME, LOC, DNAME
  FROM EMP, DEPT
  WHERE EMP.DEPTNO=DEPT.DEPTNO AND SAL>1500;

-- TASK5
SELECT ENAME, JOB, SAL, GRADE FROM EMP, SALGRADE
  WHERE SAL BETWEEN LOSAL AND HISAL;

-- TASK6
SELECT * FROM EMP, SALGRADE
  WHERE SAL BETWEEN LOSAL AND HISAL AND GRADE=3;

-- TASK7
SELECT ENAME, LOC FROM EMP
  INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
  WHERE LOC='DALLAS';

-- TASK8
SELECT ENAME FROM EMP
  INNER JOIN DEPT ON EMP.DEPTNO(+)=DEPT.DEPTNO
  WHERE DEPT.DEPTNO IN (30, 40);

-- TASK9
SELECT E1.ENAME, E1.SAL AS EMP, E2.SAL AS MANAGER FROM EMP E1, EMP E2
  WHERE E1.SAL<E2.SAL AND E1.MGR=E2.EMPNO;

-- TASK10
SELECT JOB FROM EMP
  WHERE EMP.DEPTNO=10
UNION
SELECT JOB FROM EMP
  WHERE EMP.DEPTNO=30;

-- TASK11
SELECT JOB FROM EMP
  WHERE EMP.DEPTNO=10
INTERSECT
SELECT JOB FROM EMP
  WHERE EMP.DEPTNO=30;

-- TASK12
SELECT JOB FROM EMP
  WHERE EMP.DEPTNO=10
MINUS
SELECT JOB FROM EMP
  WHERE EMP.DEPTNO=30;