-- SQL1

-- TASK1
SELECT * FROM SALGRADE;

-- TASK2
SELECT ENAME, DNAME, SAL FROM EMP
  INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
  WHERE SAL>1000 AND SAL<2000;

-- TASK3
SELECT DEPTNO, DNAME FROM DEPT
  ORDER BY DEPTNO ASC;

-- TASK4
SELECT DISTINCT JOB FROM EMP;

-- TASK5
SELECT * FROM EMP
  WHERE EMP.DEPTNO=10 OR EMP.DEPTNO=20
  ORDER BY JOB ASC;

SELECT * FROM EMP
  WHERE DEPTNO IN (10, 20)
  ORDER BY JOB;

-- TASK6
SELECT ENAME FROM EMP
  WHERE DEPTNO=20 AND JOB='CLERK';

-- TASK7
SELECT ENAME FROM EMP
  WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%LL%';

-- TASK8
SELECT ENAME, SAL FROM EMP
  WHERE SAL NOT BETWEEN 1000 AND 2000 AND LENGTH(ENAME)=5;

-- TASK9
SELECT ENAME, JOB, SAL FROM EMP
  WHERE ENAME NOT LIKE '%L%' AND SAL NOT IN (800, 1000, 3000);

-- TASK10
SELECT ENAME, JOB, SAL FROM EMP
  WHERE MGR IS NOT NULL;

-- TASK11
SELECT ENAME, SAL*12+NVL(COMM, 0) AS ANNSAL FROM EMP
  WHERE JOB='SALESMAN';

-- TASK12
SELECT ENAME FROM EMP
  WHERE JOB='MANAGER' AND DEPTNO=10;

-- TASK13
SELECT * FROM EMP
WHERE HIREDATE <= DATE '1983-01-01';

-- TASK14
SELECT ENAME, SAL*12 AS SALARY, NVL(COMM, 0) AS COMM
  FROM EMP WHERE JOB='SALESMAN' AND SAL>NVL(COMM, 0)
  ORDER BY SAL DESC, ENAME ASC;

-- TASK15
SELECT ENAME || ' HAS HELD THE POSITION OF ' || JOB || ' IN DEPTNO ' || DEPTNO || ' FROM ' || HIREDATE
  FROM EMP;